### ISSUE TITLE
The framework will not codesign correctly when implementing

### ISSUE THREAD

**Issue by emilylaguna** [PaddleHQ/Mac-Framework-V4#1]
> ![paddle](https://user-images.githubusercontent.com/793774/45102081-b5dba100-b0e1-11e8-95a3-7cbccdcecacb.png)

After looking into this it looks like the framework structure itself is invalid because the following folders are not symlinked to the correct areas and are instead just regular folders:

> (Paddle v3 on the left, and Paddle v4 on the right)
![screen shot 2018-09-05 at 8 01 35 am](https://user-images.githubusercontent.com/793774/45102176-ede2e400-b0e1-11e8-9d52-e3f413b7feb6.png)

When I went through and manually replaced the folders with the proper symlinks the Framework codesigned correctly in Xcode.

**Comment by lvandal** [comment]
I have the same issue.

**Comment by GregularExpressions** [comment]
Thanks @emilylaguna & @lvandal - we'll look into this.

**Comment by mpaddle** [comment]
@emilylaguna @lvandal This has been fixed now. Could you please try again?

**Comment by lvandal** [comment]
@mpaddle Seems to be fixed on my end! 👍
