### ISSUE TITLE
No more licenseActivated delegate callback?

### ISSUE THREAD

**Issue by JoeriBultheel** [PaddleHQ/Mac-Framework-V4#10]
In version 3 there used to be a method called 'licenseActivated' on which we relied to handle license activations. Has this been replaced by something else in version 4? How are we supposed to handle this situation?

Thnx

**Comment by GregularExpressions** [comment]
Hey @JoeriBultheel 

What's the flow you were using the licenseActivated method for? There's likely a way to replicate in v4 that we can point out for you.

Thanks,
Greg.

**Comment by JoeriBultheel** [comment]
Hi Greg,

In the case where the trial of a user is over and no license is activated yet, the application starts up in restricted mode (some features are blocked).
So, on startup the Paddle UI starts up and the two possible flows are 

	1. close (not “quit" because we use paddleProduct.willContinueAtTrialEnd = true) and thus continue in restricted “free” mode.
	2. activate license.

So in the case the user decides to go for the license we need a callback for when the user has finished buying/activating a license, so that we can trigger our application to go to unrestricted mode.

All clear? Let me know.

Thanks,
Joeri

**Comment by GregularExpressions** [comment]
For anyone visiting this issue in future, the suggested solution was to use the delegate method `didDismissPaddle` and check the `PADTriggeredUIType`:

```swift
func didDismissPaddle(_ uiType: PADUIType, triggeredUIType: PADTriggeredUIType, product: PADProduct) -> Void {
      if (triggeredUIType == PADTriggeredUIType.activated)
      {
          print("an active activation!");
      }
}
```
