### ISSUE TITLE
Wrong German localisation of Button for cancelling sheet

### ISSUE THREAD

**Issue by depth42** [PaddleHQ/Mac-Framework-V4#12]
When opening the checkout for a subscription with the new Paddle framework 4.0.1, the button for closing the sheet is named "Kündigen" in German. The correct term would be "Abbrechen" (Abort). "Kündigen" only means to cancel a contract, not to close a sheet. This used to be correct in the v3 framework.

<img width="720" alt="screen shot 2018-09-18 at 16 03 16" src="https://user-images.githubusercontent.com/207403/45693091-95d5c400-bb5c-11e8-9325-aa5c1b9088b4.png">

**Comment by GregularExpressions** [comment]
Thanks for the report Frank, we'll get that corrected for the next release.

**Comment by GregularExpressions** [comment]
Hey Frank, this should be corrected in [v4.0.2](https://github.com/PaddleHQ/Mac-Framework-V4/releases/tag/v4.0.2).
