### ISSUE TITLE
Scary autolayout messages after successful purchase

### ISSUE THREAD

**Issue by etresoft** [PaddleHQ/Mac-Framework-V4#14]
This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes.
 Stack:(
	0   Foundation                          0x00007fff4e2f3bfb _AssertAutolayoutOnAllowedThreadsOnly + 201
	1   Foundation                          0x00007fff4e2f3842 -[NSISEngine _optimizeWithoutRebuilding] + 61
	2   Foundation                          0x00007fff4e074631 -[NSISEngine optimize] + 108
	3   Foundation                          0x00007fff4e2f0d35 -[NSISEngine performPendingChangeNotifications] + 84
	4   AppKit                              0x00007fff4957e3a4 -[NSWindow(NSConstraintBasedLayout) updateConstraintsIfNeeded] + 102
	5   AppKit                              0x00007fff49607dca -[NSWindow(NSConstraintBasedLayout) layoutIfNeeded] + 83
	6   AppKit                              0x00007fff496189eb -[NSWindow displayIfNeeded] + 218
	7   AppKit                              0x00007fff495fb9e4 -[NSWindow _changeKeyAndMainLimitedOK:] + 389
	8   AppKit                              0x00007fff49676ca8 -[NSWindow _orderOutAndCalcKeyWithCounter:stillVisible:docWindow:] + 1261
	9   AppKit                              0x00007fff495fec0c NSPerformVisuallyAtomicChange + 146
	10  AppKit                              0x00007fff49dac833 -[NSWindow _doWindowOrderOutWithWithKeyCalc:forCounter:orderingDone:docWindow:] + 85
	11  AppKit                              0x00007fff49dadd26 -[NSWindow _reallyDoOrderWindowOutRelativeTo:findKey:forCounter:force:isModal:] + 446
	12  AppKit                              0x00007fff496068ec -[NSWindow _reallyDoOrderWindow:relativeTo:findKey:forCounter:force:isModal:] + 172
	13  AppKit                              0x00007fff49605765 -[NSWindow _doOrderWindow:relativeTo:findKey:forCounter:force:isModal:] + 287
	14  AppKit                              0x00007fff496055cb -[NSWindow orderWindow:relativeTo:] + 169
	15  AppKit                              0x00007fff49dab40e -[NSWindow _finishClosingWindow] + 479
	16  AppKit                              0x00007fff4974aed8 -[NSWindow _close] + 378
	17  Paddle                              0x00000001005b2af7 -[PADCheckoutWindowController closeDialog:internalUICloseReason:] + 322
	18  Paddle                              0x00000001005b2781 __57-[PADCheckoutWindowController completeCheckout:andEmail:]_block_invoke + 786
	19  Paddle                              0x00000001005b6614 __40+[PADOrderStatusPoller poll:completion:]_block_invoke_2 + 188
	20  Paddle                              0x00000001005b508c __48-[PADCheckoutApi requestOrderStatus:completion:]_block_invoke + 113
	21  Paddle                              0x00000001005b4c2e __61-[PADCheckoutApi call:method:unencodedParameters:completion:]_block_invoke + 336
	22  CFNetwork                           0x00007fff4ae6784b __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 19
	23  CFNetwork                           0x00007fff4ae670a5 __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 147
	24  Foundation                          0x00007fff4e0565df __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	25  Foundation                          0x00007fff4e056441 -[NSBlockOperation main] + 68
	26  Foundation                          0x00007fff4e0548ee -[__NSOperationInternal _start:] + 778
	27  libdispatch.dylib                   0x000000010062bd8f _dispatch_client_callout + 8
	28  libdispatch.dylib                   0x000000010063f829 _dispatch_block_invoke_direct + 576
	29  libdispatch.dylib                   0x000000010062bd8f _dispatch_client_callout + 8
	30  libdispatch.dylib                   0x000000010063f829 _dispatch_block_invoke_direct + 576
	31  libdispatch.dylib                   0x000000010063f5c9 dispatch_block_perform + 109
	32  Foundation                          0x00007fff4e0508fc __NSOQSchedule_f + 342
	33  libdispatch.dylib                   0x000000010062bd8f _dispatch_client_callout + 8
	34  libdispatch.dylib                   0x00000001006403d2 _dispatch_continuation_pop + 940
	35  libdispatch.dylib                   0x000000010063741a _dispatch_async_redirect_invoke + 738
	36  libdispatch.dylib                   0x000000010062dbea _dispatch_root_queue_drain + 723
	37  libdispatch.dylib                   0x000000010062d8c3 _dispatch_worker_thread3 + 116
	38  libsystem_pthread.dylib             0x00000001006a816d _pthread_wqthread + 1387
	39  libsystem_pthread.dylib             0x00000001006a7bed start_wqthread + 13
)

**Comment by GregularExpressions** [comment]
Hey John,

Thanks for the report, we're having trouble replicating this - are you seeing it consistently or are you able to provide any additional steps?

Thanks,
Greg.

**Comment by etresoft** [comment]
Every time. Usuually 3 or 4 stack traces after the purchase window dismisses. It seems pretty straightforward. There shouldn’t ever be network operations directly calling UI operations. I haven’t seen any corruption or wierd crashes. But people are going to see that.

**Comment by GregularExpressions** [comment]
Hey John,

Do you mind sharing some details about your implementation please? How are you invoking the flow that ends this way? It seems like there could be a threading issue somewhere.

Thanks,
Greg.

**Comment by etresoft** [comment]
Here is my purchase code. This is being called on the main thread. That last "completePurchase:" method does some background work, but I don't see how that would change anything.

```
  NSString * paddleVendorID = @"xxx";
  NSString * paddleAPIKey = @"xxx";

  PADProductConfiguration * defaultProductConfig =
    [PADProductConfiguration new];
    
  defaultProductConfig.vendorName = @"Etresoft, Inc.";
  defaultProductConfig.productName = [self productName: productCode];
  defaultProductConfig.currency = @"CAD";
  
  defaultProductConfig.price =
    [self.storeProducts[productCode] objectForKey: @"price"];

  NSLocale * locale = [NSLocale currentLocale];
  
  NSString * currencyCode =
    [locale objectForKey: NSLocaleCurrencyCode];

  defaultProductConfig.currency = currencyCode;

  Paddle * paddle =
    [Paddle
      sharedInstanceWithVendorID: paddleVendorID
      apiKey: paddleAPIKey
      productID: paddleProductID
      configuration: defaultProductConfig];
    
  paddle.delegate = self;
  
  PADProduct * paddleProduct =
    [[PADProduct alloc]
      initWithProductID: paddleProductID
      productType: PADProductTypeSDKProduct
      configuration: nil];

  [paddleProduct
    refresh:
      ^(NSDictionary * _Nullable productDelta, NSError * _Nullable error)
        {
        PADCheckoutOptions * options = [PADCheckoutOptions options];
        
        options.quantity = @1;
        options.allowQuantity = NO;
        options.message = NSLocalizedString(@"purchasemessage", NULL);
        
        [paddle
          showCheckoutForProduct: paddleProduct
          options: options
          checkoutStatusCompletion:
            ^(PADCheckoutState state,
              NSDictionary * _Nullable checkoutData)
              {
              if(state == PADCheckoutPurchased)
                {
                [self completePurchase: productCode data: checkoutData];
                }
              else if(state == PADCheckoutAbandoned)
                self.purchaseCancelled = YES;
              }];
        }];

  [paddleProduct release];

```

**Comment by etresoft** [comment]
Nevermind. I switched to the old SDK and this problem is gone. There were other problems, but I managed to beat them into submission.
