### ISSUE TITLE
Better Error Messages

### ISSUE THREAD

**Issue by jessegrosjean** [PaddleHQ/Mac-Framework-V4#16]
When I try to activate a license with an invalid license code of length 5 or less I get a relatively nice error message saying:

> Error
> A valid license code is required. Please try again.

But if I try with a longer license such as "aaaaaa". Then it seems to take a different code route. It darkens for a second (I guess contacting server) and then it just reports an empty error dialog.

I think this is happening at least when:

1. Completely invalid license.
2. All license activations are used up.
3. Maybe more cases, that's just what I've noticed.

This is causing a lots of confusion for my users. They just report to me that "licensing broken", when it's really the case that they've just used up activations, or entered an invalid code. All the error codes reported by Paddle licensing should be as clear and descriptive as possible.

**Comment by GregularExpressions** [comment]
Hey Jesse,

Thanks for the report, this could be the SDK switching between local and remote validation and the remote error not making it back to our UI in some cases.

I think this should be quite high priority, we'll try and get it fixed in the next release.

Thanks,
Greg.

**Comment by GregularExpressions** [comment]
@jessegrosjean just to confirm, this was fixed a few releases ago 👍
