### ISSUE TITLE
Trials can be extended by setting back date/time in System Preferences

### ISSUE THREAD

**Issue by tjosten** [PaddleHQ/Mac-Framework-V4#17]
I just stumbled over what seems to be a major issue to me: When setting back date/time in the macOS System preferences, trials seem to be able to extended indefinitely. For my product with a 7 day trial length set up in both the code as well as the Vendor Dashboard, setting back the time 2 weeks ended up to a remaining trial length of 14 days.

**Comment by tjosten** [comment]
Just re-tested this with v3, and it will end the trial instead of extend it.

**Comment by GregularExpressions** [comment]
Thanks for the report Timo, we'll look into this.

**Comment by lukele** [comment]
Currently simply deleting the paddle file allows to re-start the trial period... no need to set any time back

**Comment by GregularExpressions** [comment]
We're working on some improvements here which are likely to be in the next release or two.

**Comment by GregularExpressions** [comment]
We've made improvements to trials around the system clock in v4.0.4, additional trial and SDK storage improvements are coming soon to address the other concerns.

**Comment by lukele** [comment]
Does that also solve the issue with deleting the paddle file?

**Comment by GregularExpressions** [comment]
@lukele no, not yet - this is coming soon. We have to be cautious with any amendments to how the SDK stores information or state as we could accidentally invalidate trials, remove activations, etc.

**Comment by GregularExpressions** [comment]
@lukele just an update to let you know that this is still coming, we're taking some extra time with the testing.

**Comment by lukele** [comment]
Thank you for the update! Much appreciated. Looking forward to this
