### ISSUE TITLE
Paddle v.4 not working with macOS 10.10 and 10.11

### ISSUE THREAD

**Issue by Iomegan** [PaddleHQ/Mac-Framework-V4#18]
Guys,

when using 
`sharedInstanceWithVendorID:apiKey:productID:configuration:`
the Paddle framework calls
 [`scheduledTimerWithTimeInterval:repeats:block:`](https://developer.apple.com/documentation/foundation/nstimer/2091889-scheduledtimerwithtimeinterval)
which is only available on macOS 10.12 or higher.

Since this method is essential to use Paddle, 10.10 and 10.11 do not work with the latest version of the framework.

Cheers

**Comment by GregularExpressions** [comment]
Hey Daniel

Thanks for the report, we're not sure how Xcode snuck this past us given the versions we're targeting! We will get this corrected in the next release.

Greg.

**Comment by Iomegan** [comment]
Thanks.

**Comment by Iomegan** [comment]
Quick question: A version with Paddle v4 has already been shipped when I noticed this bug. Is it possible to downgrade back to V3 with no issues for users who registered the app with V4 and never used a version of my app that had V3?

**Comment by cazoobi** [comment]
Yeah I also found the SDK throwing an error on 10.11, this is from the logs..

+[NSTimer scheduledTimerWithTimeInterval:repeats:block:]: unrecognized selector sent to class 0x7fff75033a88

**Comment by Iomegan** [comment]
To answer my own question:
> A version with Paddle v4 has already been shipped when I noticed this bug. Is it possible to downgrade back to V3 with no issues for users who registered the app with V4 and never used a version of my app that had V3?

Yes it is possible to downgrade. At least I cloud find no issues with that.

**Comment by GregularExpressions** [comment]
Hey Everyone,

A v4 release will go out shortly that addresses this compatibility issue, if you're using our license keys then we'd expect issues when downgrading as we've improved the file formats and local storage in v4.

Thanks,
Greg.
