### ISSUE TITLE
Paddle keeps showing the 'Continue Trial' button even when the product trial is disabled

### ISSUE THREAD

**Issue by emilylaguna** [PaddleHQ/Mac-Framework-V4#2]
I've tried manually setting the trial to none in the `PADProductConfiguration` object but that didn't work either. I can see in the API response that the trial is disabled as well but the `showProductAccessDialogWithProduct` always shows the Continue Trial button. Clicking this button results in the Paddle window closing but then nothing else happens, the app doesn't show, no other code is ran, etc.

**Comment by GregularExpressions** [comment]
Hey @emilylaguna thanks for the report, we'll look into this and get back to you.

**Comment by GregularExpressions** [comment]
Hey @emilylaguna can you retest this on [v4.0.1](https://github.com/PaddleHQ/Mac-Framework-V4/releases) please?
