### ISSUE TITLE
Crash during payment process

### ISSUE THREAD

**Issue by lvandal** [PaddleHQ/Mac-Framework-V4#24]
I received a crash report about Paddle crashing while the customer was purchasing our app via PayPal.

[b3feee690958c5e0983ea9252bd8fe90.log](https://github.com/PaddleHQ/Mac-Framework-V4/files/2431517/b3feee690958c5e0983ea9252bd8fe90.log)

**Comment by lvandal** [comment]
I'm currently using v4.0.2 and I see that 4.0.3 seems to solve the same or similar issue. I'll give that a try.

**Comment by GregularExpressions** [comment]
thanks @lvandal let us know.

**Comment by lvandal** [comment]
There are still some WebKit related crashes occurring during the purchase process. The logs don't seem to include anything from Paddle but the user told me that it occurred while purchasing our app. 

We're using v4.0.3.

[b4fae6c61e5ed490262ad04c802ad611.log](https://github.com/PaddleHQ/Mac-Framework-V4/files/2465164/b4fae6c61e5ed490262ad04c802ad611.log)

**Comment by lvandal** [comment]
Here's another one from today:

"Completing purchase from within trial mode of app downloaded from your site."

[53f10bcaad0bd677dfb736ab2c5c7127.log](https://github.com/PaddleHQ/Mac-Framework-V4/files/2474004/53f10bcaad0bd677dfb736ab2c5c7127.log)

**Comment by core-code** [comment]
it seems both crash reports you've got and all 3 i've got are from customers running 10.14. 

since 10.14 doesn't have THAT high a marketshare yet, this could be a clue.

**Comment by GregularExpressions** [comment]
@core-code, @lvandal we'll look at this as a priority on Monday.

**Comment by core-code** [comment]
thanks, i'm attaching another crash report

[c3.txt](https://github.com/PaddleHQ/Mac-Framework-V4/files/2476557/c3.txt)

**Comment by core-code** [comment]
got another crash. any progress?

**Comment by core-code** [comment]
thanks, very happy you are closing in on that crash.

**Comment by core-code** [comment]
any progress on a new release?

**Comment by GregularExpressions** [comment]
hey @core-code this release will be out today 👍

**Comment by GregularExpressions** [comment]
@core-code & @lvandal this should be fixed in [v4.0.4](https://github.com/PaddleHQ/Mac-Framework-V4/releases/tag/v4.0.4) let us know if you continue to see issues.

**Comment by core-code** [comment]
@GregularExpressions thanks! will soon ship an update with this and will let you know
