### ISSUE TITLE
Cannot accelerate trials?

### ISSUE THREAD

**Issue by lvandal** [PaddleHQ/Mac-Framework-V4#3]
I've tried to set `PaddleAccelerateTrial` to `YES` in Terminal like I used to with V3 but it doesn't seem to work in V4.

**Comment by lvandal** [comment]
Ok. How would you suggest testing end of trials and resetting activations in the meantime?

**Comment by avalore** [comment]
Hey @lvandal 

In the latest release `4.0.1` you can enable debug `[Paddle enableDebug];`, which will display a Debug menu bar. From there you can choose to expire or reset trials for testing.

**Comment by lvandal** [comment]
Entering the product ID has no effect. Perhaps I'm doing something wrong?

<img width="532" alt="screen shot 2018-09-18 at 9 05 05 am" src="https://user-images.githubusercontent.com/157723/45689492-1aefb780-bb22-11e8-9d85-e7aaf05907aa.png">

**Comment by GregularExpressions** [comment]
Hey @lvandal can you give us a bit more info about the flow/process you're doing please?

**Comment by tjosten** [comment]
@GregularExpressions My app is a menu bar app and thus has no window with a menu bar. How can I access the debug menu to accelerate trials?

**Comment by tjosten** [comment]
I would be a fine with a debug window that I can either make appear by calling a function, or that automatically appears when debug mode is enabled.

**Comment by GregularExpressions** [comment]
Thanks @tjosten that sounds feasible to me, we'll consider it as an option.
