### ISSUE TITLE
Paddle 4.0.4 shows an empty alert dialogue when user tries to activate product with a wrong serial number

### ISSUE THREAD

**Issue by core-code** [PaddleHQ/Mac-Framework-V4#30]
while paddle v3 would properly explain something like 'license can not be found' , paddle v3 just shows an empty alert dialoge when the user tries to activate our product with a license that does not exist

<img width="532" alt="screenshot 2018-10-22 at 17 07 11" src="https://user-images.githubusercontent.com/1261954/47300615-3405ef80-d61d-11e8-857d-06dc66ef6e29.png">

**Comment by GregularExpressions** [comment]
thanks @core-code, apologies for the inconvenience - we'll get this corrected.

**Comment by core-code** [comment]
awesome, thanks

**Comment by lvandal** [comment]
Still occurs. In our case, the user had no activations left. Not a very good UX you will agree!

<img width="532" alt="screenshot 2018-10-30 at 23 14 38" src="https://user-images.githubusercontent.com/157723/47754566-a86e0d80-dc71-11e8-99ce-6901a550ce88.png">

**Comment by GregularExpressions** [comment]
@lvandal yes, whilst this seems like it could just be a misplaced localized string it's part of a larger issue about how the SDK surfaces errors to the developer and to the end users. We're taking this opportunity to improve it, it should be completed soon.

**Comment by GregularExpressions** [comment]
As of [v4.0.5](https://github.com/PaddleHQ/Mac-Framework-V4/releases/tag/v4.0.5) this error is no-longer blank 👍

**Comment by core-code** [comment]
thanks i'll update in the next release

**Comment by core-code** [comment]
thanks i am trying to update to 4.0.5 because this bug was fixed. however, i am having troubles migrating because the API seems to have changed. previously i was using:

        PADLicenseMigrate *lm = [PADLicenseMigrate new];
        lm.delegate = self;
        [lm locateAndMigrateExistingV3License:MYPRODUCTID];

however this seems no longer possible. can you share some replacement code?

**Comment by GregularExpressions** [comment]
@core-code apologies, we modified the v3 migration experience to give Sellers more control (there was an accidental race condition in one implementation we helped troubleshoot). The docs are due soon but I'll get a reply in here with the changes for you today 👍

**Comment by core-code** [comment]
@GregularExpressions thanks, looking forward to it ;)

**Comment by core-code** [comment]
thanks, i'll give it another shot for our next release

**Comment by core-code** [comment]
> To migrate a v3 license with the new process, you need to instantiate a `PADProduct` instance and call `migrateV3License` on that product instance.

just wanted to let you know that this seems to work fine here - thanks
