### ISSUE TITLE
Does this most recent update fix the crashing problem?

### ISSUE THREAD

**Issue by etresoft** [PaddleHQ/Mac-Framework-V4#31]
It takes people's money and then promptly crashes the app. For some reason, people don't like that.

    Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
    0   libobjc.A.dylib               	0x00007fff6db3759d objc_msgSend + 29
    1   com.apple.WebKitLegacy        	0x00007fff5042f187 -[_WebSafeForwarder forwardInvocation:] + 71
    2   com.apple.CoreFoundation      	0x00007fff41b3753c ___forwarding___ + 762
    3   com.apple.CoreFoundation      	0x00007fff41b371b8 _CF_forwarding_prep_0 + 120
    4   com.apple.WebKitLegacy        	0x00007fff50431f94 -[WebHTMLView drawSingleRect:] + 564
    5   com.apple.WebKitLegacy        	0x00007fff50431b84 -[WebHTMLView drawRect:] + 436
    6   com.apple.AppKit              	0x00007fff3f152205 _NSViewDrawRect + 66
    7   com.apple.AppKit              	0x00007fff3f150abd -[NSView(NSInternal) _recursive:displayRectIgnoringOpacity:inContext:shouldChangeFontReferenceColor:stopAtLayerBackedViews:] + 1545
    8   com.apple.WebKitLegacy        	0x00007fff5051d0d1 -[WebHTMLView(WebPrivate) _recursive:displayRectIgnoringOpacity:inContext:shouldChangeFontReferenceColor:stopAtLayerBackedViews:] + 113
    9   com.apple.AppKit              	0x00007fff3f1504a2 __46-[NSView(NSLayerKitGlue) drawLayer:inContext:]_block_invoke + 192
    10  com.apple.AppKit              	0x00007fff3f150201 -[NSView(NSLayerKitGlue) _drawViewBackingLayer:inContext:drawingHandler:] + 1769
    11  com.apple.WebKitLegacy        	0x00007fff50437016 -[WebHTMLView(WebInternal) drawLayer:inContext:] + 118
    12  com.apple.QuartzCore          	0x00007fff4ca93aaf CABackingStoreUpdate_ + 577
    13  com.apple.QuartzCore          	0x00007fff4caf5325 invocation function for block in CA::Layer::display_() + 53
    14  com.apple.QuartzCore          	0x00007fff4ca92c90 -[CALayer _display] + 1839
    15  com.apple.AppKit              	0x00007fff3f14f75a _NSBackingLayerDisplay + 531
    16  com.apple.AppKit              	0x00007fff3f133cc9 -[_NSViewBackingLayer display] + 811
    17  com.apple.QuartzCore          	0x00007fff4ca921bc CA::Layer::display_if_needed(CA::Transaction*) + 634
    18  com.apple.QuartzCore          	0x00007fff4ca80447 CA::Context::commit_transaction(CA::Transaction*) + 319
    19  com.apple.QuartzCore          	0x00007fff4ca7fd20 CA::Transaction::commit() + 576
    20  com.apple.AppKit              	0x00007fff3f12a8f5 __65+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayRefresh]_block_invoke + 274
    21  com.apple.CoreFoundation      	0x00007fff41b3c709 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
    22  com.apple.CoreFoundation      	0x00007fff41b3c63e __CFRunLoopDoObservers + 452
    23  com.apple.CoreFoundation      	0x00007fff41ade4e2 __CFRunLoopRun + 1173
    24  com.apple.CoreFoundation      	0x00007fff41adddfa CFRunLoopRunSpecific + 467
    25  com.apple.HIToolbox           	0x00007fff40d69895 RunCurrentEventLoopInMode + 293
    26  com.apple.HIToolbox           	0x00007fff40d695cb ReceiveNextEventCommon + 618
    27  com.apple.HIToolbox           	0x00007fff40d69348 _BlockUntilNextEventMatchingListInModeWithFilter + 64
    28  com.apple.AppKit              	0x00007fff3f02695b _DPSNextEvent + 997
    29  com.apple.AppKit              	0x00007fff3f0256fa -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1362
    30  com.apple.AppKit              	0x00007fff3f01f75d -[NSApplication run] + 699
    31  com.apple.AppKit              	0x00007fff3f00ee97 NSApplicationMain + 780
    32  libdyld.dylib                 	0x00007fff6ec0c085 start + 1

**Comment by GregularExpressions** [comment]
Hey @etresoft 

Thanks for the report, I can confirm we believe this issue is resolved in [v4.0.4](https://github.com/PaddleHQ/Mac-Framework-V4/releases/tag/v4.0.4).

Please let us know if you continue to experience it after updating.

Thanks,
Greg.

**Comment by etresoft** [comment]
I've never experienced it. It doesn't happen when you pay with a coupon, which is what I always test with. But when real people pay with real money, it fails 23% of the time.

I sure hope this new build does better.

**Comment by etresoft** [comment]
I can confirm that the crash is not resolved. Luckily, I have a Mac App Store version of my app. I've pulled the link to the Paddle version altogether. I would rather lose 30% to Apple and have happy customers than give refunds to the 23% of my customer that think I'm an idiot. 

Now I have to go back through my database and hand about about $750 in refunds.

**Comment by etresoft** [comment]
I'm attaching the full crash report. If you want a copy of the build, you can download it at (https://etrecheck.com/details). Better do it fast because I have my own embedded web view almost ready to go. 

This is an in-app purchase. It doesn't deliver the content until after payment completes. It doesn't deliver said content because the app crashes. I guess you could call that "poor UX". It doesn't crash while using a coupon, which is why I didn't notice it.

Note that this is not a full SDK integration. I've been leery about having too much integration and dependence on Paddle. Those fears were justified. I'm lucky that I can just throw together a web view to fix the problem. I'm doubly lucky that I can just change my download link to point to the Mac App Store while I fix the problem. Otherwise, I would really be in a pickle right now, wouldn't I?

[EtreCheckPro_2018-10-25-095857_Jessicas-Mac-mini.crash.zip](https://github.com/PaddleHQ/Mac-Framework-V4/files/2525819/EtreCheckPro_2018-10-25-095857_Jessicas-Mac-mini.crash.zip)

**Comment by GregularExpressions** [comment]
@etresoft We are having trouble replicating in your app, can you provide steps please? At the moment we don't seem to be able to trigger an in-app purchase?

**Comment by etresoft** [comment]
1. Click on "Choose a problem" and pick anything other than "No problem - just checking"
2. Click "Start EtreCheck"
3. Wait
4. Click "See solution"
5. Click "Buy Solution CAD $ 15.99"

Don't use a coupon. I've run this with a coupon many times and it has never failed.

**Comment by GregularExpressions** [comment]
Thanks @etresoft 

We've been having a look at the build you linked us to, it appears to be on v4.0.3. The fix was shipped in v4.0.4, do you have a build with that SDK version in that has had reports of the crash?

**Comment by etresoft** [comment]
It looks like there was an older version of the framework in the Xcode directory. Bummer. In any event, I've learned my lesson about using someone else's code in my app. I've already got my own SDK working.

**Comment by own2pwn** [comment]
Hey @GregularExpressions did you manage to solve this issue? I'm having the versy same issue on my ios app (though it's not related to Paddle)
