### ISSUE TITLE
White blinking in UI

### ISSUE THREAD

**Issue by charlieMonroe** [PaddleHQ/Mac-Framework-V4#35]
Please, see this video: https://cl.ly/c408be8a275f

When I launch the app in dark mode under Mojave, initially, the window is white and then the dark UI appears.

**Comment by GregularExpressions** [comment]
Thanks for the report @charlieMonroe & @tunabelly we know what this is, it'll be fixed for the next release.

**Comment by GregularExpressions** [comment]
Hey Charlie & Matt, (if you hadn't already seen) this is fixed as of [v4.0.6](https://github.com/PaddleHQ/Mac-Framework-V4/releases/tag/v4.0.6) 👍
