### ISSUE TITLE
[Question] PADProduct "activated" state after "licenseExpiryDate" reached?

### ISSUE THREAD

**Issue by waleeg** [PaddleHQ/Mac-Framework-V4#36]
Hi,

Just a simple question. 

Once my license expiry date has passed, is the `activated` property set to `true` or `false` on the `PADProduct`?

Thanks for your work.

**Comment by GregularExpressions** [comment]
Hey @waleeg, currently the `activated` property doesn't take license expiry dates into effect. A previously activated product with a now expired license will still return `true`.

Products have a `licenseExpiryDate` property that you can use to confirm that it's both active and non-expired.

Hope that helps.
Greg.

**Comment by waleeg** [comment]
Awesome thanks @GregularExpressions! 👍🏻

You can close the issue ✅
