### ISSUE TITLE
Localization issues

### ISSUE THREAD

**Issue by charlieMonroe** [PaddleHQ/Mac-Framework-V4#37]
Hi,

in French, the activation button is cut off. Debugging the UI and looking at constraints, this button has a fixed width to 120. The same goes for the text field above the price - it's fixed size to 63. This makes the UI really poorly localizable...

<img width="536" alt="screen shot 2018-12-04 at 7 41 30 am" src="https://user-images.githubusercontent.com/64899/49423610-594b5900-f798-11e8-9e4c-d35fa38ef5d9.png">

**Comment by charlieMonroe** [comment]
And in German, it's the left button.

<img width="536" alt="screen shot 2018-12-04 at 7 51 55 am" src="https://user-images.githubusercontent.com/64899/49424005-8f3d0d00-f799-11e8-9942-62aee20bfc9a.png">

**Comment by GregularExpressions** [comment]
Hey @charlieMonroe 

Thanks for the report, this is good timing. We're going to spend some time on improving the UI layouts and localisation soon 👍

Greg.

**Comment by charlieMonroe** [comment]
Awesome, thanks!

**Comment by Iomegan** [comment]
This seems to be a never ending issue that has existed in v3 long before. Please do tests for all localisations. :)

**Comment by Iomegan** [comment]
<img width="536" alt="bildschirmfoto 26" src="https://user-images.githubusercontent.com/1634465/49744521-3f7cab00-fc9d-11e8-856c-0f12711498eb.png">
it should be "Von Vendor" not "Nach vendor" in the German localisation. People asking me if I used Google Translate... 😕

**Comment by Iomegan** [comment]
Only the title is translated in the error message that shows up if a user enters a wrong email address:
<img width="491" alt="bildschirmfoto 43" src="https://user-images.githubusercontent.com/1634465/50792170-5c1ff900-12c4-11e9-97d4-7947ea11f700.png">

**Comment by Iomegan** [comment]
Please fix the button issues and possibly the other localisation issues with the next update. That shouldn't be too complicated.

**Comment by GregularExpressions** [comment]
@Iomegan we've got the vast majority of these resolved for the next release, there's some debate around the translation of "okay" to German. Do you have an opinion / suggestion on that?

**Comment by Iomegan** [comment]
On macOS "Okay" is usually not being used in English but especially not in German. Apple usually uses "OK" in English and also "OK" in German. Although it is not 100% German, it Is known by every German user.

So use "OK" for German and maybe consider using it in English as well.

And in general:
> Avoid using OK for the default button unless the alert is purely informational.
[Human Interface Guidelines - Alerts](https://developer.apple.com/design/human-interface-guidelines/macos/windows-and-views/alerts/)

**Comment by GregularExpressions** [comment]
Hi Everyone,

We've prepared a beta that we believe addresses most, if not all of the above. If anyone has time to take a look before we make it into a general release it would be appreciated 👍

[macOS-sdk-beta.zip](https://github.com/PaddleHQ/Mac-Framework-V4/files/2767890/macOS-sdk-beta.zip)

Thanks,
Greg.

**Comment by Iomegan** [comment]
Thanks. I've looked at the English and German localisation.

<img width="547" alt="screenshot 48" src="https://user-images.githubusercontent.com/1634465/51337349-267acd00-1a87-11e9-8e01-bf19ae32b37d.png">
Should be: "Wie oft möchten Sie "Network Radar" erwerben?"

If you fix that, the only missing part left that is not translated will be the trialText. There's a separate ticket for that [here](https://github.com/PaddleHQ/Mac-Framework-V4/issues/39).

**Comment by GregularExpressions** [comment]
Thanks for having a look @Iomegan!

The text you've highlighted is actually supplied by our checkout dynamically, and has been fixed in an upcoming release for that - so that'll just sort itself out in future without an SDK release.

`trialText` requires us to have a think about the best way to approach it in the SDK, we want to avoid these conflicts between local and remote - it's on our radar.

**Comment by GregularExpressions** [comment]
[v4.0.8](https://github.com/PaddleHQ/Mac-Framework-V4/releases/tag/v4.0.8) has significant localization improvements 👍
