### ISSUE TITLE
License Verification Issues

### ISSUE THREAD

**Issue by charlieMonroe** [PaddleHQ/Mac-Framework-V4#38]
I check for the license validity in my products each launch but since v4 I have received several complaints that the app locked the user out. I asked for some logs and discovered this:

```
XUAppDelegate+PaddleDelegate.swift:242.verifyLicense(): Unverified license [0]: Error Domain=com.paddle.paddle Code=-108 "Specifies that we were unable to verify the license activation of a product." UserInfo={NSLocalizedDescription=Specifies that we were unable to verify the license activation of a product.}.
```

According to the log this happened on each launch, in this case 21 times in a row.

I've asked the user to verify that they have access to both paddle.com and paddleapi.com - both load in their browsers as well as in the app (it includes an in-app browser). Unless v4 is using a different server, this is not a network issue.

Removing the license files and reactivating fixes the issue. I.e. the issue is very likely in the migrated license file? Can it get corrupted?

If you can check this against your server logs I can provide you with the emails/license codes (privately via email, of course).

**Comment by GregularExpressions** [comment]
Hey @charlieMonroe 

Thanks for the report, we'll look into it - please do email me the license code 👍

Greg.

**Comment by GregularExpressions** [comment]
@charlieMonroe I believe this is resolved, I'll close this issue. Let us know if it persists.
