### ISSUE TITLE
Show product access dialog as sheet?

### ISSUE THREAD

**Issue by lvandal** [PaddleHQ/Mac-Framework-V4#4]
This used to be possible in V3. Anyway to do this in V4? Also, I've been trying to accelerate the trial (issue #3)  in order to see if the dialog will be modal and block any interaction with opened windows but it doesn't seem to work.

**Comment by mpaddle** [comment]
Hi @lvandal, it is possible to show dialogs as sheets by implementing the `PaddleDelegate` method `willShowPaddleUIType:(PADUIType)uiType product:(nonnull PADProduct *)product`. In the implemented method, if you return a display configuration with a display type of `PADDisplayTypeSheet` and specify a window, then the dialog will be shown as a sheet.

Are you using Objective-C or Swift? I can add code snippets in this thread, if that helps.

**Comment by lvandal** [comment]
@mpaddle Using this works like a charm:

`func willShowPaddle(_ uiType: PADUIType, product: PADProduct) -> PADDisplayConfiguration? {
    return PADDisplayConfiguration(displayType: .sheet, hideNavigationButtons: false, parentWindow: self.window!)
    }`

**Comment by mpaddle** [comment]
@lvandal That's perfect 👍

**Comment by waleeg** [comment]
I couldn't find anything regarding showing paddle window as a sheet in the documentation. 
It would be nice to add it if it is not there. 👍🏻
