### ISSUE TITLE
/Users/Shared/ directory?

### ISSUE THREAD

**Issue by etresoft** [PaddleHQ/Mac-Framework-V4#41]
Apparently the Paddle framework creating a directory in /Users/Shared. One of my customers asked me about such a directory and my app isn’t doing it. Apparently Paddle is creating it [https://github.com/PaddleHQ/Mac-Framework/issues/194#issuecomment-390942728](url). I’m not using Paddle’s licensing so it should not be creating this directory.

**Comment by GregularExpressions** [comment]
Hey @etresoft can you confirm the version of the SDK you're using please? This _sounds_ like it could be a v3 issue?

Thanks,
Greg.

**Comment by etresoft** [comment]
I’m using 4.0.4. I just double-checked that. And I forgot to mention that I used “strings” to look at the Paddle framework binary and there is a "Shared/%@“ in the binary.

**Comment by GregularExpressions** [comment]
Thanks @etresoft we know what this is, at the moment the file handle we use will create the directory if it doesn't find it.

This would happen automatically in earlier v4 versions and will now only happen if a "check for v3" call is triggered - however, we probably still shouldn't create the directory if it isn't there.

We'll raise as a bug and resolve.

**Comment by etresoft** [comment]
Thanks! And to clarify, is this something that is fixed in 4.0.6 right now?

**Comment by GregularExpressions** [comment]
Yes, assuming you're not triggering the v3 -> v4 migration 👍

**Comment by etresoft** [comment]
As far as I know I’m not doing that. It should be easy enough to test now that I know about it.

**Comment by GregularExpressions** [comment]
@etresoft this is fixed in [v4.0.8](https://github.com/PaddleHQ/Mac-Framework-V4/releases/tag/v4.0.8) 👍
