### ISSUE TITLE
Wrong Error Handling with invalid API credentials

### ISSUE THREAD

**Issue by sebakotiv** [PaddleHQ/Mac-Framework-V4#50]
I try to handle the situation, where my existing API key is not valid anymore.

I see 2 issues here:

### Wrong API Key

- I created Paddle.sharedInstance with existing vendor ID but wrong API key
- I instantiate PADProduct object with an existing activation
- Now when I try to verify the activation with myProduct.verifyActivation() I get:
state -> PADVerificationState.unverified
error -> code=-108, Specifies that we were unable to verify the license activation of a product
In this case I would expect state to be "unableToVerify" and the error PADAPIErrorBadAPIKey (code 102)

I also get an error in my PaddleDelegate paddleDidError:
Code=-112
"Specifies that the product appears to be unreleased or incomplete in the Paddle dashboard"
which is also not really correct.

And where is no place there I get the expected error PADAPIErrorBadAPIKey.

###  Wrong vendorId on Paddle.sharedInstance
In this case it looks like only the API key is used for identification and it succeeded. No error will be returned.
What is the purpose of passing venderId in the initialisation method then?

**Comment by GregularExpressions** [comment]
Hey @sebakotiv thanks for the report.

We agree that `PADAPIErrorBadAPIKey` would be better for the case you've outlined, we'll look at improving this.

`VendorID` is a required parameter on some of our API endpoints, we collect it upfront in the initialisation and then include it payloads automatically.

**Comment by GregularExpressions** [comment]
@sebakotiv We've added PADAPIErrorBadAPIKey to [v4.0.10](https://github.com/PaddleHQ/Mac-Framework-V4/releases/tag/v4.0.10) 👍
