### ISSUE TITLE
How to get checkout data(PADCheckoutdata) information after user purchase ?

### ISSUE THREAD

**Issue by premkolindala** [PaddleHQ/Mac-Framework-V4#51]
[Paddle.sharedInstance showProductAccessDialogWithProduct:self->paddleProduct];
 after calling this shows paddle window with product details but what i want is when user purchase from here i want PADCheckout data.

**Comment by GregularExpressions** [comment]
Hey @premkolindala thanks for the question.

You were correct that this wasn't possible, we've added a new method to the `PADProduct` delegate of `productPurchased:` that should help with this.

Can you have a look at this [Beta](https://s3.amazonaws.com/paddle-production-sdk-releases/macOS/v4/beta/macOS-sdk-beta.zip) and let me know if it does what you need please?

**Comment by premkolindala** [comment]
yeah !! i am getting chekout_id using this Beta version SDk .  
i am getting order details `https://checkout.paddle.com/api/1.0/order?checkout_id=xxxxxx` using this api thanks for patch but can i use this `beta` SDK for my live apps ?

**Comment by GregularExpressions** [comment]
@premkolindala glad to hear it has resolved your issue for now. `productPurchased:` is only called when the `PADCheckoutState` is `PADCheckoutPurchased` so the state would always be the same.

What's the use case you're after?

We'll do a production release of the SDK in the next few days with this so you can ship it.

**Comment by premkolindala** [comment]
ok cool waiting for next release  and when i could expect the next possible release.

**Comment by GregularExpressions** [comment]
@premkolindala we're hoping today or Monday.

**Comment by premkolindala** [comment]
Thanks!!! @GregularExpressions

**Comment by GregularExpressions** [comment]
@premkolindala this'll be released on Tuesday.

**Comment by GregularExpressions** [comment]
@premkolindala this is in [v4.0.10](https://github.com/PaddleHQ/Mac-Framework-V4/releases/tag/v4.0.10) 👍
