### ISSUE TITLE
v4.0.9 - `licenseExpiryDate` always nil

### ISSUE THREAD

**Issue by waleeg** [PaddleHQ/Mac-Framework-V4#52]
Hi,

I have updated from `v4.0.8` to `v4.0.9`, since then `licenseExpiryDate` on the `PADProduct` is always `nil`.
I am unable to validate the license for my users.

I am accessing `licenseExpiryDate` after a refresh, within the completion block. Am I missing something?

I have downgraded the framework in the meantime. 

Thanks

**Comment by GregularExpressions** [comment]
@waleeg thanks for the report! Apologies for the inconvenience, here's a [Beta](https://s3.amazonaws.com/paddle-production-sdk-releases/macOS/v4/beta/macOS-sdk-beta.zip). If you could confirm that it resolves the problem for you then we'll ship v4.0.10 with the fix.

**Comment by waleeg** [comment]
@GregularExpressions thanks for the prompt reply. It seems to fix the problem 👍

**Comment by GregularExpressions** [comment]
@waleeg thanks for confirming, we'll ship v4.0.10 in the next day or so.

**Comment by GregularExpressions** [comment]
@waleeg this fix is in [v4.0.10](https://github.com/PaddleHQ/Mac-Framework-V4/releases/tag/v4.0.10) 👍
