### ISSUE TITLE
infinite loop while trying to 'register' using Paddle

### ISSUE THREAD

**Issue by core-code** [PaddleHQ/Mac-Framework-V4#57]
hello there,

i received this from a customer:

> when I was trying to enter my license info, it got stuck in a loop. I kept putting in my details and hitting Register, but then the window closed and just re-opened again. I had to force quit the app and then restart it, after that the license was in. I had the exact same problem with another app that uses the Paddle registration framework (/name redacted/). I contacted the developer and he fixed the issue- I think there was an updated version of the framework maybe that fixes it. I compared the you use with the one in /name redacted/) and I noticed he's using v4.0.10 while you have v4.0.9.  So maybe that's it? 

i didn't find anything in the release notes for 4.0.10 about this though. this is quite light on details, but is this something you've heard about and/or fixed in 4.0.10? 

thanks!

**Comment by GregularExpressions** [comment]
Hey @core-code 

Thanks for the report, we've not had anyone else mention this and we've not seen it ourselves - so none of the changes in v4.0.10 were _designed_ to resolve this.

After upgrading, let us know if you get more reports like this.

Thanks,
Greg.

**Comment by core-code** [comment]
thanks, will do.
