### ISSUE TITLE
PADErrorUnreleasedProductFromAPI

### ISSUE THREAD

**Issue by tjosten** [PaddleHQ/Mac-Framework-V4#7]
Hi,

when calling `[product refresh:]` on a product (that is a subscription and has been sold multiple times successfully with the v3 SDK), the error -112 which seems to translate to PADErrorUnreleasedProductFromAPI is thrown.

The description is interesting:

    /**
     * @brief Specifies that the product appears to be unreleased or incomplete in the Paddle dashboard.
     * @discussion This error is generated when the product data is refreshed and the remote product data
     * indicates that the product has been configured completely.
     */

That reads odd, I guess there is a *not* missing?

**Comment by GregularExpressions** [comment]
@tjosten Thanks for your patience on this, you're correct - we'll amend the comment in a future release 👍

**Comment by tjosten** [comment]
@GregularExpressions Thanks, but the comment is not my concern. Is the issue with refreshing subscription products fixed?
