### ISSUE TITLE
Crashes when attempting to activate the license while offline

### ISSUE THREAD

**Issue by ianbytchek** [PaddleHQ/Mac-Framework-V4#76]
Not receiving an error, just crashing the entire app… Perfect!

```swift
product.activateEmail(email, license: license, completion: { success, error in })
```

**Comment by JoMarques09** [comment]
@ianbytchek Can you tell us what version of the SDK are you currently on and also is this happening on the Catalina, Mojave or both?

**Comment by ianbytchek** [comment]
PaddleV4 (4.0.13)
macOS Mojave 10.14.6 (18G103)
Didn't try this on Catalina.

**Comment by JoMarques09** [comment]
@ianbytchek  Thank you for sending that across, in order to help us investigate this further, would you also be able to send us a crash report?

**Comment by ahmaniea** [comment]
4.0.14 seems to have fixed this.

**Comment by JoMarques09** [comment]
Yes @ahmaniea that is correct the latest release contains the fix for this issue https://github.com/PaddleHQ/Mac-Framework-V4/releases
